# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.box = "sugar7-php54"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 9200, host: 9300
  config.vm.network "forwarded_port", guest: 3306, host: 9306


  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"


# VM specs for VirtualBox 
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "3072"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # VM specs for VMware Fusion
  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "3072"
    v.vmx["numvcpus"] = "2"
  end

  # VM specs for VMware Workstation
  config.vm.provider "vmware_workstation" do |v|
    v.vmx["memsize"] = "3072"
    v.vmx["numvcpus"] = "2"
  end

end
